global using Carter;
global using Mapster;
global using MediatR;
global using Marten;
global using Catalog.API.Models;
global using BuildingBlocks.CQRS;
global using BuildingBlocks.Behaviors;
global using BuildingBlocks.Exceptions.Handler;
global using Catalog.API.Data;