global using Basket.API.Models;
global using BuildingBlocks.CQRS;
global using MediatR;
global using Mapster;
global using FluentValidation;
global using BuildingBlocks.Behaviors;
global using BuildingBlocks.Exceptions;
global using BuildingBlocks.Exceptions.Handler;
global using Carter;